import "@/scss/app.scss";

export const metadata = {
  title: "Redirect",
  description: "Generated by create next app",
};

export default function RedirectLayout({ children }) {
  return (
    <html lang="ru">
      <body>{children}</body>
    </html>
  );
}
